language: java
sudo: false

services:
- docker

script: 
- mvn clean package
- docker build -t fo0/spring-boot-admin:latest .
- docker run -d -p 1111:1111 --name spring-boot-admin fo0/spring-boot-admin:latest
- sleep 30
- docker exec -it spring-boot-admin sh -c "curl -f http://localhost:1111/health"
- docker logs spring-boot-admin
